version: "3"
volumes:
  servervol:
  clientvol:
services:
  server:
    volumes: 
     - servervol:/server/serverdata
    build: server/
    command: python ./server.py
    ports:
      - 1234:1234
  client:
    volumes: 
     - clientvol:/client/clientdata
    build: client/
    command: python ./client.py
    network_mode: host
    depends_on:
      - server



  